### ISSUE TITLE
_hasHadInteraction

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt-contrib-confidenceSlider#20]
What is the reason behind needing to check if the slider has been interacted with first before allowing a user to submit? This stops a user from being able to choose the first option. If they wanted to do this they would have to make an attempt to move the slider first.

Do we really need this check? It isn't used in the normal slider component.

**Comment by moloko** [comment]
+1 don't think the check should be there

**Comment by oliverfoster** [comment]
doesn't seem to be used as a reference by the linked confidence, although it does exist in the linked confidence slider.

+1 for removal

**Comment by LukaszGrela** [comment]
+1 if slider starts with already selected option than this check is invalid
