### ISSUE TITLE
turn marking on/off

### ISSUE THREAD

**Issue by tomallpress** [adaptlearning/adapt-contrib-confidenceSlider#31]
Would it be possible for the marking on the confidence slider to be updated to either:

- remove the tick/cross between the submit/show feedback buttons, and update the indicator colours used on the slider itself (green/red), as I'm not sure this strictly a question component where you can get it correct/incorrect? what are people's thoughts on that?

or

- make it all marking on this component configurable, like the other question components, using canShowMarking: true/false

Thanks in advance

**Comment by moloko** [comment]
@tomallpress you can set `_canShowMarking` on this component - setting it to `false` fixes this issue

From what I can see, if you leave `_canShowMarking` on it always marks itself as correct.

Clearly there's an argument for having the code force `_canShowMarking` to `false` - but I can also see another argument for saying that you might like to keep some visual consistency with other components that use the question buttons sets.

If we do allow for the author to choose then we should at least include `_canShowMarking` in example.json with a comment explaining how it behaves with this component

**Comment by tomallpress** [comment]
@moloko ah that's working now! yep, would be great for that to be added in to the example.json, so it's clear it's configurable on this component, thanks!
