### ISSUE TITLE
Doesn't seem to work in the Authoring Tool...

### ISSUE THREAD

**Issue by markidm** [adaptlearning/adapt-contrib-confidenceSlider#33]
No matter what options are set, I can't get the preview to work in the authoring tool with this plugin. Always receiving: Error generating preview, please contact Administrator.

My error log states: "mFatal error: Error: Module loading did not complete for: core/js/app, plugins, components/adapt-contrib-confidenceSlider/js/adapt-contrib-confidenceSlider, core$
The following modules share the same URL. This could be a misconfiguration if that URL only has one anonymous module in it:
/home/idmadapt/adapt_authoring/temp/xxxxxxxxxxxxxxxxx/adapt_framework/src/core/js/adapt.js: core/js/adapt, coreJS/adapt
    at Function.build.checkForErrors (/home/idmadapt/adapt_authoring/temp/xxxxxxxxxxxxxxxxx/adapt_framework/node_modules/requirejs/bin/r.js:28204:19)

**Comment by oliverfoster** [comment]
I'll try this in the framework. It looks as though core$ isn't defined, I''m not sure which plugin would be requesting it. I'll investigate.

**Comment by oliverfoster** [comment]
![image](https://cloud.githubusercontent.com/assets/7974663/26782313/da34874c-49ea-11e7-9e73-2bd45e6c9f63.png)

it builds fine here. could someone with access to an AT please give this component a try?

**Comment by harlows** [comment]
This is the error I get when attempting to preview in the AT:

```
Running "less:compile" (less) task
screen size: { small: 519, medium: 759, large: 1024 }
Fatal error: {
 "type": "Name",
 "filename": "src/components/adapt-contrib-confidenceSlider/less/confidenceSlider.less",
 "index": 120,
 "line": 7,
 "callLine": null,
 "column": 6,
 "extract": [
  "\t    .linked-confidence-bar {",
  "\t    \t.rangeslider__fill;",
  "\t    \tbackground-color: lighten(@item-color, 20%);"
 ],
 "message": ".rangeslider__fill is undefined"
}
```
The trick is to add the contrib-slider component to the course which presumably defines the `.rangeslider__fill` variable (HT @moloko [here](https://community.adaptlearning.org/mod/forum/discuss.php?d=1165#p6739)). It would be nice to remove this dependency.
