### ISSUE TITLE
Unable to preview course when using slider

### ISSUE THREAD

**Issue by barryjenkin** [adaptlearning/adapt-contrib-confidenceSlider#43]
Hi there.
Just struggling to get the component (v2.1.3) working in AT 0.7.0. I get a fatal error and the course fails to preview (it previews fine once component is removed). Does it need updating for the latest slider/framework?

Fatal error: {
0|server  |  "message": ".slider-component is undefined",
0|server  |  "type": "Name",
0|server  |  "filename": "src/components/adapt-contrib-confidenceSlider/less/confidenceSlider.less",
0|server  |  "index": 34,
0|server  |  "line": 2,
0|server  |  "column": 4,
0|server  |  "callLine": null,
0|server  |  "extract": [
0|server  |   ".confidenceSlider-component {",
0|server  |   "    .slider-component;",
0|server  |   ""
0|server  |  ]
0|server  | }

**Comment by moloko** [comment]
> Does it need updating for the latest slider/framework?

That has been done already, it's just that doing the actual release has fallen by the wayside. I'll try and find some time today to do that, in the meantime if you download the [master branch](https://github.com/adaptlearning/adapt-contrib-confidenceSlider/archive/master.zip) that should (hopefully) work OK
