### ISSUE TITLE
Introduce React to Confidence Slider

### ISSUE THREAD

**Issue by eleanor-heath** [adaptlearning/adapt-contrib-confidenceSlider#54]

**Comment by fosterc1** [comment]
Hello

I seem to be getting the following error:

Command failed: grunt server-build:prod --outputdir=courses/620022867fedaf12a54f48d9/620a3154ad6cc7051a94247a/build --theme=620023fbfb00cc13a3a1cb52 --menu=adapt-mindboostmenu
Error: Could not load /home/v5-predevelopment/temp/620022867fedaf12a54f48d9/adapt_framework/src/components/adapt-contrib-confidenceSlider/js/ConfidenceSliderView (imported by src/components/adapt-contrib-confidenceSlider/js/adapt-contrib-confidenceSlider.js): ENOENT: no such file or directory, open '/home/v5-predevelopment/temp/620022867fedaf12a54f48d9/adapt_framework/src/components/adapt-contrib-confidenceSlider/js/ConfidenceSliderView'

Is this the plugin?

Thanks
