### ISSUE TITLE
input element aria-label read twice in reading mode

### ISSUE THREAD

**Issue by joe-replin** [adaptlearning/adapt-contrib-confidenceSlider#70]
### Subject of the issue/enhancement/features
The input element `.js-slider-item-input` when given an aria-label reading out your previous answer in a linked confidence slider. But while in screen reader reading mode, the aria-label is read twice. Once when navigating via arrow keys, and a 2nd time when the input element is selected. I'm not sure how to solve this one but would appreciate some pointers.

### Your environment
* plug-in v5.2.0
* AF v5.19.6
* All Browsers
* JAWS & NVDA

### Steps to reproduce
Install latest version of this plug-in.
Link two confidence sliders together.
Answer the first confidence slider.
Navigate through the 2nd confidence slider with a screen reader and reading mode.

### Expected behaviour
Ideally, the aria-label should only be read upon selection for this users who tab through all the focusable elements.

### Actual behaviour
The aria-label is read before selecting the element and after.

**Comment by oliverfoster** [comment]
Superceded by native sliders.

**Comment by oliverfoster** [comment]
https://github.com/adaptlearning/adapt-contrib-confidenceSlider/commit/5eced627f8a34a62ae4e7fd276f735f0a58a62b1
