### ISSUE TITLE
Feedback no longer given

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-confidenceSlider#75]
### Subject of the issue
When used e.g. with tutor on submit there is no feedback given. I believe this problem began with adapt-contrib-core v6.20.5 due to https://github.com/adaptlearning/adapt-contrib-core/pull/223.

### Your environment
* adapt-contrib-core => v6.20.5

**Comment by fosterc1** [comment]
Agree

This was previously showing feedback and no longer is.
![2022-12-07_13-24-29](https://user-images.githubusercontent.com/29701150/206190733-b5188624-dd94-4946-bd9d-441c63dd7482.png)
